

export default [
  {
    id: '001',
    name: 'Eco-Friendly Water Bottle',
    description: 'A reusable, eco-friendly water bottle made from BPA-free materials.',
    price: 15.99,
    category: 'Home & Kitchen',
    image: "eco-friendly-water-bottle.jpg",
    alt: 'Eco-Friendly Water Bottle',
  },
  {
    id: '002',
    name: 'Eco-Friendly Water Bottle',
    description: 'A reusable, eco-friendly water bottle made from BPA-free materials.',
    price: 15.99,
    category: 'Home & Kitchen',
    image: 'eco-friendly-water-bottle.jpg',
    alt: 'Eco-Friendly Water Bottle',
  }, {
    id: '003',
    name: 'Eco-Friendly Water Bottle',
    description: 'A reusable, eco-friendly water bottle made from BPA-free materials.',
    price: 15.99,
    category: 'Home & Kitchen',
    image: 'eco-friendly-water-bottle.jpg',
    alt: 'Eco-Friendly Water Bottle',
  }, {
    id: '004',
    name: 'Eco-Friendly Water Bottle',
    description: 'A reusable, eco-friendly water bottle made from BPA-free materials.',
    price: 15.99,
    category: 'Home & Kitchen',
    image: 'eco-friendly-water-bottle.jpg',
    alt: 'Eco-Friendly Water Bottle',
  }, {
    id: '005',
    name: 'Eco-Friendly Water Bottle',
    description: 'A reusable, eco-friendly water bottle made from BPA-free materials.',
    price: 15.99,
    category: 'Home & Kitchen',
    image: 'eco-friendly-water-bottle.jpg',
    alt: 'Eco-Friendly Water Bottle',
  }, {
    id: '006',
    name: 'Eco-Friendly Water Bottle',
    description: 'A reusable, eco-friendly water bottle made from BPA-free materials.',
    price: 15.99,
    category: 'Home & Kitchen',
    image: 'eco-friendly-water-bottle.jpg',
    alt: 'Eco-Friendly Water Bottle',
  }, {
    id: '007',
    name: 'Eco-Friendly Water Bottle',
    description: 'A reusable, eco-friendly water bottle made from BPA-free materials.',
    price: 15.99,
    category: 'Home & Kitchen',
    image: 'eco-friendly-water-bottle.jpg',
    alt: 'Eco-Friendly Water Bottle',
  }, {
    id: '008',
    name: 'Eco-Friendly Water Bottle',
    description: 'A reusable, eco-friendly water bottle made from BPA-free materials.',
    price: 15.99,
    category: 'Home & Kitchen',
    image: 'eco-friendly-water-bottle.jpg',
    alt: 'Eco-Friendly Water Bottle',
  },
  {
    id: '009',
    name: 'Eco-Friendly Water Bottle',
    description: 'A reusable, eco-friendly water bottle made from BPA-free materials.',
    price: 15.99,
    category: 'Home & Kitchen',
    image: 'eco-friendly-water-bottle.jpg',
    alt: 'Eco-Friendly Water Bottle',
  },
  {
    id: '010',
    name: 'Eco-Friendly Water Bottle',
    description: 'A reusable, eco-friendly water bottle made from BPA-free materials.',
    price: 15.99,
    category: 'Home & Kitchen',
    image: 'eco-friendly-water-bottle.jpg',
    alt: 'Eco-Friendly Water Bottle',
  },
  
  
];
